---
version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    commands:
      - echo "Instalando kubectl"
      - set -e
      - >
        curl -fsSL -o /usr/local/bin/kubectl
        "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"
      - chmod +x /usr/local/bin/kubectl
      - echo "Verificando kubectl"
      - file /usr/local/bin/kubectl || true
      - >
        head -c 4 /usr/local/bin/kubectl | hexdump -C || true
      - >
        kubectl version --client --output=yaml ||
        (echo 'kubectl inválido' && exit 1)

  pre_build:
    commands:
      - echo "Login no ECR"
      - aws --version
      - >
        ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
        export ECR_URI
      - >
        aws ecr get-login-password --region $AWS_DEFAULT_REGION |
        docker login --username AWS --password-stdin $ECR_URI
      - >
        COMMIT_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
        export COMMIT_TAG
      - echo "CommitTag=$COMMIT_TAG"

  build:
    commands:
      - echo "Buildando imagem..."
      - docker build -t $ECR_URI:$COMMIT_TAG -t $ECR_URI:latest .

  post_build:
    commands:
      - echo "Fazendo push..."
      - docker push $ECR_URI:$COMMIT_TAG
      - docker push $ECR_URI:latest
      - >
        printf '{"ImageURI":"%s"}' "$ECR_URI:$COMMIT_TAG" >
        imageDetail.json
      - echo "Configurando kubeconfig para $EKS_CLUSTER_NAME"
      - >
        aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
        --region $AWS_DEFAULT_REGION
      - echo "Lendo imagem do imageDetail.json..."
      - >
        IMAGE_URI=$(python -c
        'import json,sys,os; p=os.path.join(os.getcwd(),"imageDetail.json");
        print(json.load(open(p))["ImageURI"])')
        export IMAGE_URI
      - echo "Nova_imagem=$IMAGE_URI"
      - test -n "$IMAGE_URI" ||
        (echo 'IMAGE_URI vazio' && exit 1)
      - >
        kubectl -n $KUBERNETES_NAMESPACE set image
        deployment/todo-list-app todo-list-app=$IMAGE_URI
      - >
        kubectl -n $KUBERNETES_NAMESPACE rollout status
        deployment/todo-list-app --timeout=120s

artifacts:
  files:
    - imageDetail.json
    - k8s/*.yaml
  name: build-output
